- name: Join K3s Cluster on Worker Nodes
  hosts: workers
  become: yes
  tasks:
    - name: Join K3s Cluster
      shell: |
        curl -sfL https://get.k3s.io | K3S_URL=https://{{ hostvars['master'].ansible_host }}:6443 K3S_TOKEN={{ hostvars['master'].k3s_token.stdout }} sh -
